from enum import Enum

class StatusChat(Enum): 
  ATIVO = 'ATIVO'
  AGUARDANDO_ACEITE = 'AGUARDANDO_ACEITE'
  SOLICITACAO_PENDENTE = 'SOLICITACAO_PENDENTE'
  ENCERRADO = 'ENCERRADO'
  
class MensagemSocket(Enum):
  SOLICITAR_CONEXAO = 'SOLICITAR_CONEXAO'
  ACEITAR_CONEXAO = 'ACEITAR_CONEXAO'